config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :playgrounds
  get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playground.rb
class Playground < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  before_action :set_playground, only: %i[ show edit update destroy ]

  # GET /playgrounds or /playgrounds.json
  def index
    @playgrounds = Playground.all
  end

  # GET /playgrounds/1 or /playgrounds/1.json
  def show
  end

  # GET /playgrounds/new
  def new
    @playground = Playground.new
  end

  # GET /playgrounds/1/edit
  def edit
  end

  # POST /playgrounds or /playgrounds.json
  def create
    @playground = Playground.new(playground_params)

    respond_to do |format|
      if @playground.save
        format.html { redirect_to @playground, notice: "Playground was successfully created." }
        format.json { render :show, status: :created, location: @playground }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playground.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playgrounds/1 or /playgrounds/1.json
  def update
    respond_to do |format|
      if @playground.update(playground_params)
        format.html { redirect_to @playground, notice: "Playground was successfully updated." }
        format.json { render :show, status: :ok, location: @playground }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playground.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playgrounds/1 or /playgrounds/1.json
  def destroy
    @playground.destroy
    respond_to do |format|
      format.html { redirect_to playgrounds_url, notice: "Playground was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playground
      @playground = Playground.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playground_params
      params.require(:playground).permit(:name, :phone, :email, :twitter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hom_helper.rb
module HomHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playgrounds_helper.rb
module PlaygroundsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">

    <%# NAVIGATION TO ROOT  `rails routes` %>
    <%= link_to 'Playground', root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">

        <%= link_to 'About Us', home_about_path, class: "nav-link" %>
        
        </li>

         <li class="nav-item">

        <%= link_to 'Show Data', playgrounds_path, class: "nav-link" %>
        
        </li>

         <li class="nav-item">

        <%= link_to 'Add Data', new_playground_path, class: "nav-link" %>
        
        </li>

        <li class="nav-item">

        <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
        
        </li>

        <li class="nav-item">

        <%= link_to 'Sign In', new_user_session_path, class: "nav-link" %>
        
        </li>

        <li class="nav-item">

        <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link" %>
        
        </li>

        <li class="nav-item">

        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us </h1>

app/views/home/index.html.erb
<h1>Hello World</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  
  <%= notice  %>

  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Playground</title>
 
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">


    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <%= render 'home/header' %>
    <div class="container">
    
      <br/>

      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
      <%# <p>SOME FOOTER</p> %>

      <footer>
        <%# <p>Author: John Melody <a href="mailto:johnmelody@dingtalk.com">[ Johnmelody@dingtalk.com ]</a> </p>  %>
      </footer> 
    </div>
    
    
  </body>
</html>

app/views/playgrounds/_form.html.erb
<%= form_with(model: playground) do |form| %>
  <% if playground.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(playground.errors.count, "error") %> prohibited this playground from being saved:</h2>

      <ul>
        <% playground.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :name, class:"form-control", placeholder:"Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>
<br/>
  <div class="actions">
    <%= form.submit class:"btn btn-dark" %>
  </div>
<% end %>

app/views/playgrounds/edit.html.erb
<h1>Editing Playground</h1>

<%= render 'form', playground: @playground %>

<%= link_to 'Show', @playground %> |
<%= link_to 'Back', playgrounds_path %>

app/views/playgrounds/index.html.erb
<h1>Playgrounds Data List</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Twitter</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @playgrounds.each do |playground| %>
      <tr>
        <td><%= playground.name %></td>
        <td><%= playground.phone %></td>
        <td><%= playground.email %></td>
        <td><%= playground.twitter %></td>
        <td><%= link_to 'Display', playground, class:"btn btn-dark" %></td>
        <td><%= link_to 'Adment', edit_playground_path(playground), class:"btn btn-dark" %></td>
        <td><%= link_to 'Delete', playground, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New Data', new_playground_path, class:"btn btn-dark"%>

app/views/playgrounds/new.html.erb
<h1>Add New Data</h1>
<br/>

<%= render 'form', playground: @playground %>
<br/>
<%= link_to 'Back', playgrounds_path, class:"btn btn-dark" %>

app/views/playgrounds/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">
    <%= @playground.name %>
  </h1>
  <p class="lead">
  
  <strong>Phone:</strong>  
  <%= @playground.phone %> |

  <strong>Email:</strong>  
  <%= @playground.email %>  | 

  <strong>Twitter:</strong>  
  <%= @playground.twitter %>  |

  </p>

  <%= link_to 'Edit', edit_playground_path(@playground), class:"btn btn-dark"%>
  <%= link_to 'Back', playgrounds_path, class:"btn btn-dark" %>
</div>